/**
 * TestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DescribedThing from './Model/DescribedThing';
import Thing from './Model/Thing';
import DefaultApi from './Api/DefaultApi';


/**
* Client library for BitPesa API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BitpesaSdk = require('index'); // See note below*.
* var xxxSvc = new BitpesaSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BitpesaSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BitpesaSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BitpesaSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DescribedThing model constructor.
     * @property {module:Model/DescribedThing}
     */
    DescribedThing,

    /**
     * The Thing model constructor.
     * @property {module:Model/Thing}
     */
    Thing,

    /**
    * The DefaultApi service constructor.
    * @property {module:Api/DefaultApi}
    */
    DefaultApi
};
