/**
 * TestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Thing model module.
 * @module Model/Thing
 * @version 0.1.0
 */
class Thing {
    /**
     * Constructs a new <code>Thing</code>.
     * The root of the Thing type&#39;s schema.
     * @alias module:Model/Thing
     * @param name {String} 
     */
    constructor(name) { 
        
        Thing.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Thing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/Thing} obj Optional instance to populate.
     * @return {module:Model/Thing} The populated <code>Thing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Thing();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
Thing.prototype['name'] = undefined;






export default Thing;

